name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.AI_REVIEW_PAT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
          # optional
          LANGUAGE: Korean
          MODEL: gpt-4o-mini-2024-07-18 # https://platform.openai.com/docs/models
          IGNORE_PATTERNS: /node_modules,*.md,/**/*.stories.tsx # Regex pattern to ignore files, separated by comma
